### ISSUE TITLE
nginx Log Spam with PHP 8.3

### ISSUE THREAD

**Issue by vmario89** [SS88UK/roundcube-easy-unsubscribe#10]
Hi, i recognized that the plugin makes a lot of extra lines on nginx log:

```
webmail.redacted.org, request: "POST /?_task=mail&_action=refresh HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.3-fpm.sock:", host: "webmail.redacted.org"
2024/11/14 21:30:14 [error] 690205#690205: *907408 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "fetch_headers" in /var/www/vhosts/webmail.redacted.org/plugins/easy_unsubscribe/easy_unsubscribe.php on line 28" while reading response header from upstream, client: 79.198.141.199, server: webmail.redacted.org, request: "POST /?_task=mail&_action=refresh HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.3-fpm.sock:", host: "webmail.redacted.org"
```

i am using Roundcube 1.6.9 with PHP 8.3 on Ubuntu 20 Focal. Any idea? i am not sure if this warning is new or old. But it creates really large logs. 

i checked that code line in easy_unsubscribe.php but i am not sure what i should do here to fix or mute that warning

**Comment by Neoboffin** [comment]
Hey @vmario89,

I've updated the file `easy_unsubscribe.php` with the change; this should fix the issue that's going into the log files.

https://github.com/SS88UK/roundcube-easy-unsubscribe/blob/a161ec7afa7a85e9094f6ef835f1db572b181293/easy_unsubscribe.php#L28

**Comment by vmario89** [comment]
thank you very much for your quick look at this. you fixed it! thanks to you
