### ISSUE TITLE
Outdated version at plugins.roundcube.net

### ISSUE THREAD

**Issue by emtiu** [SS88UK/roundcube-easy-unsubscribe#7]
This plugin is listed at https://plugins.roundcube.net/#/packages/ss88/easy_unsubscribe and https://packagist.org/packages/ss88/easy_unsubscribewith the latest `dev-master` commit 3970c08.

However, when using composer to install it, the information at https://plugins.roundcube.net/p/ss88/easy_unsubscribe%243eca1312a1595c6ebfe5e178c043d8ac8348a541df6381c8a9aea41b9f62b0d9.json is referenced by composer, which is outdated and lists d09f442 from 2019 as the latest commit.

There must be something weird going on for the [Roundcube Plugins web frontend](https://plugins.roundcube.net/#/packages/ss88/easy_unsubscribe) and [its actual hosted json version information](https://plugins.roundcube.net/p/ss88/easy_unsubscribe%243eca1312a1595c6ebfe5e178c043d8ac8348a541df6381c8a9aea41b9f62b0d9.json) to disagree.

Because of this, I've found it impossible to install the latest version through composer.

(I've opened the same Issue against the Roundcube Plugins Repo: https://github.com/roundcube/plugins2.roundcube.net/issues/35)

**Comment by Neoboffin** [comment]
Thanks for having a look at this @emtiu; I'm going to wait to see what happens at Roundcube. I did manually log into packagist.org just now and hit the update button. I am not sure if that fixed the issue for you.

**Comment by emtiu** [comment]
Thanks for that! The situation is unchanged as far as I can see, but I'm running with your code installed manually for the moment :)

**Comment by emtiu** [comment]
Update: There are workarounds, which involve telling `composer.json` not to use plugins.roundcube.net, but rather the default repo at packagist.org. The problem is being discussed [here](https://github.com/roundcube/plugins2.roundcube.net/issues/35) and [here](https://github.com/roundcube/roundcubemail/issues/9323).

As things stand, easy_unsubscribe will always be installed as the outdated https://github.com/SS88UK/roundcube-easy-unsubscribe/commit/d09f4428aeb6763dd4110a59e32cfcb231174c8b from 2019, because Roundcube's default `composer.json` refers to plugins.roundcube.net.

You probably cannot help the situation, so feel free to close this Issue, or keep it open in case other users run into similar problems :)

**Comment by Neoboffin** [comment]
Thanks for digging into this @emtiu! I'm wondering if I should change the `composer.json` file I have in the repo to exclude `plugins.roundcube.net` also?

**Comment by emtiu** [comment]
> I'm wondering if I should change the `composer.json` file I have in the repo to exclude `plugins.roundcube.net` also?

Oh, I hadn't even noticed that one before. Yeah, that's probably a good move—plugins.roundcube.net definitely isn't being maintained anymore.

**Comment by Neoboffin** [comment]
Got it, I'll remove it now! Thank you once again!
